Repository cse112-sp20/Team-Potato, pull requests merged in 2020-06, with the labels that each got.

#141 Focus Mode Slider to set time
  package-lock.json
  package.json
  src/components/PopupFocusMode.jsx
  src/styles/PopupFocusMode.css
Labels: UI/Design

#144 Update CC and Add Jest Test Coverage
  .circleci/config.yml
  test/tabgroup_CRUD_issue#34.py
Labels: build_process

#136 ui improve 2. made menu page match more like tabs
  .circleci/config.yml
  src/background.js
  src/components/Menu.jsx
  src/components/Popup.jsx
  src/components/PopupFocusMode.jsx
  src/components/TabGroup.jsx
  src/siteBlocker.js
  src/styles/BlockPopup.css
  src/styles/Menu.css
  src/styles/Popup.css
  src/styles/PopupFocusMode.css
  src/styles/Tab.css
  src/styles/TabGroup.css
  test/Menu.test.js
  test/Popup.test.js
Labels: feature

#157 Overlay Bug with Gradescope
  src/components/PopupFocusMode.jsx
  src/styles/BlockPopup.css
Labels: bug
